[package]
name = "demos"
version = "0.1.0"
authors = ["guoxbin <guoxbin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trie-db = "0.20.0"
reference-trie = "0.20.0"
memory-db = "0.19.0"
keccak-hasher = "0.15.2"
parity-codec = "4.1.4"
parity-codec-derive = "3.3.0"
smallvec = "1.2.0"
hash-db = "0.15.2"
log = "*"
